import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await p.waitForTimeout(900)
await p.locator('.card .pic').first().click()
await p.waitForTimeout(600)
await p.screenshot({ path: '/tmp/m1.png' })
await p.evaluate(() => document.querySelector('.modal').scrollTo(0, 600))
await p.waitForTimeout(400)
await p.screenshot({ path: '/tmp/m2.png' })
await p.locator('.modal .x').click()
await p.locator('.dd-btn.wide').click()
await p.waitForTimeout(500)
await p.screenshot({ path: '/tmp/m3.png' })
await b.close()
