import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 950 } })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1200)
await p.screenshot({ path: '/tmp/k1-hero.png' })
await p.evaluate(() => document.querySelector('.sales').scrollIntoView())
await p.waitForTimeout(900)
await p.screenshot({ path: '/tmp/k2-sales.png' })
await p.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await p.waitForTimeout(1100)
await p.screenshot({ path: '/tmp/k3-catalog.png' })
await p.locator('.card .pic').nth(2).click()
await p.waitForTimeout(500)
await p.screenshot({ path: '/tmp/k4-modal.png' })
await p.locator('.modal .x').click()
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
await p.waitForTimeout(700)
await p.screenshot({ path: '/tmp/k5-foot.png' })
await b.close()
