import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } })
const errs = []
p.on('pageerror', e => errs.push(e.message.slice(0, 120)))
p.on('response', r => r.status() >= 400 && errs.push(`${r.status()} ${r.url().slice(0, 80)}`))
await p.goto('https://azizatavaliev-bot.github.io/glowly/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1800)
await p.screenshot({ path: '/tmp/p1.png' })
await p.fill('.hero-search input', 'тонер')
await p.waitForTimeout(700)
console.log('подсказки:', await p.locator('.hero-hits button:not(.all) b').allTextContents())
await p.evaluate(() => document.querySelector('#routine').scrollIntoView())
await p.waitForTimeout(600)
await p.locator('.rb-opt').nth(1).click()
await p.locator('.rb-opt').nth(6).click()
await p.waitForTimeout(900)
await p.screenshot({ path: '/tmp/p2.png' })
console.log('ошибки:', errs.length ? errs : 'нет')
await b.close()
