import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 950 } })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1500)
await p.screenshot({ path: '/tmp/h1.png' })
await p.evaluate(() => window.scrollBy(0, 500))
await p.waitForTimeout(800)
await p.screenshot({ path: '/tmp/h2.png' })
await b.close()
