// сценарий покупателя на телефоне: два товара в корзину → панель корзины → текст заказа для WhatsApp
import { chromium } from 'playwright'
const b = await chromium.launch()
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto(process.argv[2] || 'http://localhost:5280/', { waitUntil: 'networkidle' })
await m.evaluate(() => { localStorage.removeItem('lilo.cart'); document.querySelector('#catalog').scrollIntoView() })
await m.waitForTimeout(900)
await m.locator('.catalog .card .buy').nth(0).click()
await m.locator('.catalog .card .buy').nth(0).click()   // первая кнопка стала счётчиком, это уже второй товар
await m.locator('.catalog .card .stepper.wide button').nth(1).click()
await m.waitForTimeout(500)
await m.locator('.catalog .card').first().scrollIntoViewIfNeeded()
await m.evaluate(() => scrollBy(0, 330))
await m.waitForTimeout(500)
await m.screenshot({ path: '/tmp/cart-1.png' })
await m.locator('.mbar-cart').click()
await m.waitForTimeout(700)
await m.screenshot({ path: '/tmp/cart-2.png' })
const href = await m.locator('.cart .wa-btn').getAttribute('href')
console.log(href.split('?')[0]); console.log(decodeURIComponent(href.split('text=')[1]))
await m.locator('.cart .x').click()
await m.locator('.catalog .card .pic').nth(2).click()
await m.waitForTimeout(900)
await m.screenshot({ path: '/tmp/cart-3.png' })
console.log('overflow', await m.evaluate(() => document.documentElement.scrollWidth - innerWidth))
await b.close()
