import { chromium } from 'playwright'
const b = await chromium.launch()
const d = await b.newPage({ viewport: { width: 1440, height: 1000 } })
const errs = []
d.on('pageerror', e => errs.push(e.message.slice(0, 120)))
await d.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await d.evaluate(() => document.querySelector('#top').scrollIntoView())
await d.waitForTimeout(900)
await d.screenshot({ path: '/tmp/t1.png' })
await d.goto('http://localhost:5280/?p=566', { waitUntil: 'networkidle' })
await d.waitForTimeout(900)
await d.screenshot({ path: '/tmp/t2.png' })
await d.goto('http://localhost:5280/?p=528', { waitUntil: 'networkidle' })
await d.waitForTimeout(700)
console.log('цена 528 в карточке:', await d.locator('.price.big').textContent())
const m = await b.newPage({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await m.waitForTimeout(1200)
await m.screenshot({ path: '/tmp/t3.png' })
console.log('ошибки:', errs.length ? errs : 'нет')
await b.close()
