import { chromium } from 'playwright'
const b = await chromium.launch()
const errs = []
const d = await b.newPage({ viewport: { width: 1440, height: 1000 } })
d.on('pageerror', e => errs.push(e.message.slice(0, 120)))
await d.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await d.waitForTimeout(1500)
await d.screenshot({ path: '/tmp/f15-1.png' })
await d.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await d.waitForTimeout(900)
await d.screenshot({ path: '/tmp/f15-2.png' })
console.log('в каталоге:', await d.locator('.found b').first().textContent(), '· карточек:', await d.locator('.card').count())
await d.evaluate(() => document.querySelector('#routine').scrollIntoView())
await d.locator('.rb-opt').nth(1).click(); await d.locator('.rb-opt').nth(6).click()
await d.waitForTimeout(800)
console.log('конструктор собрал шагов:', await d.locator('.rb-step .rb-name').count(), '/ 5')
const m = await b.newPage({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await m.waitForTimeout(1200)
await m.screenshot({ path: '/tmp/f15-3.png' })
console.log('ошибки:', errs.length ? errs : 'нет')
await b.close()
