import { chromium } from 'playwright'
const b = await chromium.launch()
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto('http://localhost:5280/?brand=ARIUL', { waitUntil: 'networkidle' })
await m.waitForTimeout(1200)
await m.evaluate(() => document.querySelector('.catalog .card').scrollIntoView())
await m.waitForTimeout(900)
await m.screenshot({ path: '/tmp/fu-m1.png' })
await m.locator('.card .pic').first().click()
await m.waitForTimeout(900)
await m.screenshot({ path: '/tmp/fu-m2.png' })
const d = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
await d.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await d.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await d.waitForTimeout(1200)
await d.screenshot({ path: '/tmp/fu-d1.png' })
const ov = await d.evaluate(() => document.documentElement.scrollWidth - innerWidth)
console.log('overflow', ov, 'cards', await d.locator('.card').count())
await b.close()
