import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } })
const errs = []
p.on('pageerror', e => errs.push(e.message.slice(0, 120)))
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1200)
await p.screenshot({ path: '/tmp/cl1.png' })
await p.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await p.waitForTimeout(900)
await p.screenshot({ path: '/tmp/cl2.png' })
await p.locator('.card .pic').first().click()
await p.waitForTimeout(700)
await p.screenshot({ path: '/tmp/cl3.png' })
await p.evaluate(() => document.querySelector('.modal').scrollTo(0, 900))
await p.waitForTimeout(400)
await p.screenshot({ path: '/tmp/cl4.png' })
await p.locator('.modal .x').click()
await p.evaluate(() => document.querySelector('.how').scrollIntoView())
await p.waitForTimeout(700)
await p.screenshot({ path: '/tmp/cl5.png' })
console.log('ошибки:', errs.length ? errs : 'нет')
await b.close()
