import { chromium } from 'playwright'
const b = await chromium.launch()
const d = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 })
await d.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await d.waitForTimeout(1500)
await d.screenshot({ path: '/tmp/lg-d.png' })
await d.screenshot({ path: '/tmp/lg-d-zoom.png', clip: { x: 60, y: 0, width: 420, height: 80 } })
await d.evaluate(() => document.querySelector('footer').scrollIntoView())
await d.waitForTimeout(600)
await d.screenshot({ path: '/tmp/lg-foot.png' })
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await m.waitForTimeout(1200)
await m.screenshot({ path: '/tmp/lg-m1.png' })
await m.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await m.waitForTimeout(900)
await m.screenshot({ path: '/tmp/lg-m2.png' })
await b.close()
