import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.evaluate(() => document.querySelector('.needs').scrollIntoView())
await p.waitForTimeout(900)
await p.screenshot({ path: '/tmp/nd1.png' })
await p.locator('.need').nth(0).click()
await p.waitForTimeout(900)
await p.screenshot({ path: '/tmp/nd2.png' })
await p.fill('.search', 'крем от прыщей')
await p.waitForTimeout(700)
console.log('крем от прыщей →', await p.locator('.found b').first().textContent())
await p.fill('.search', 'rhtv')
await p.waitForTimeout(600)
console.log('rhtv (раскладка) →', await p.locator('.found b').first().textContent())
await p.fill('.search', 'увлажнение')
await p.waitForTimeout(600)
console.log('увлажнение →', await p.locator('.found b').first().textContent())
await b.close()
