import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1200)
await p.screenshot({ path: '/tmp/mb1.png' })
await p.evaluate(() => document.querySelector('.needs').scrollIntoView())
await p.waitForTimeout(800)
await p.screenshot({ path: '/tmp/mb2.png' })
await p.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await p.waitForTimeout(800)
await p.screenshot({ path: '/tmp/mb3.png' })
await p.locator('.card .pic').first().click()
await p.waitForTimeout(800)
await p.screenshot({ path: '/tmp/mb4.png' })
await b.close()
