import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1050 } })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await p.fill('.search', 'sunscreen')
await p.waitForTimeout(700)
await p.locator('.card .pic').first().click()
await p.waitForTimeout(600)
await p.screenshot({ path: '/tmp/m4.png' })
await b.close()

const b2 = await chromium.launch()
const m = await b2.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await m.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await m.evaluate(() => document.querySelector('#catalog').scrollIntoView())
await m.waitForTimeout(600)
await m.locator('.card .pic').first().click()
await m.waitForTimeout(600)
await m.screenshot({ path: '/tmp/m5.png' })
await m.evaluate(() => document.querySelector('.modal').scrollTo(0, 700))
await m.waitForTimeout(400)
await m.screenshot({ path: '/tmp/m6.png' })
await b2.close()
