import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1400, height: 1000 } })
await p.goto('http://localhost:5280/', { waitUntil: 'networkidle' })
await p.screenshot({ path: '/tmp/korshop-1.png' })
await p.locator('.card .pic').first().click()
await p.waitForTimeout(400)
await p.screenshot({ path: '/tmp/korshop-2.png' })
await p.locator('.modal .add').click()
await p.locator('.modal .x').click()
await p.locator('.card .add').nth(1).click()
await p.locator('.cart-btn').click()
await p.waitForTimeout(400)
await p.screenshot({ path: '/tmp/korshop-3.png' })
await b.close()
